spring.application.name=gestao-cursos

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_cursos_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
